name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
      - name: Setup PHP SDK with Developer Pack
        uses: zephir-lang/setup-php-sdk@fd5f1bce00956a7e8ac30faaa1ff0692d6dacdfb # v1.0
        with:
          php_version: '8.4'
          ts: 'nts'
          msvc: 'vs16'
          arch: 'x64'
          install_dir: 'C:\tools'
          cache_dir: 'C:\Temp'
      - name: Clone PHP-src
        run: |
          git clone https://github.com/php/php-src.git C:\php-src
      - name: Clone source
        run: |
          git clone https://github.com/NoiseByNorthwest/php-spx.git C:\php-src\ext\php-spx
      - name: Configure and build 1
        run: |
          cd C:\php-src\ext\php-spx
          git checkout release/latest
      - name: Configure and build 2
        run: |
          move config.w32 C:\php-src\ext\php-spx
          cd C:\php-src
          ./buildconf.bat
      - name: Configure and build 3
        run: |
          cd C:\php-src
          ./configure --help
          ./configure --disable-all --enable-cli --enable-spx
      - name: Configure and build 4
        run: |
          cd C:\php-src
          nmake

